---
name: Lingua-FR-Fathom
version: 0.01
author:
  - 'Jean-Francois Leforestier URC HEGP Paris XV <jean-francois.leforestier@egp.aphp.fr>'
abstract: Measure readability of French text
license: perl
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Lingua::FR::Fathom:
    file: lib/Lingua/FR/Fathom.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
